### ISSUE TITLE
Ajout de la liste de l'exec sur le site

### ISSUE THREAD

**Issue by ldionmarcil** [dciets/dciets.github.io#6]
Tel que mentionné par des commanditaires potentiels et inb4, personne sait qui est dans l'exec. Faudrait ajouter une liste des membres et leurs rôles à quelque part sur le site.

**Comment by dannytranlx** [comment]
Références: 
* http://jekyllrb.com/docs/collections/
* https://github.com/lanets/lanets.github.io/blob/new-new-design/_data/authors.yml

Utilisez une collection et sur la page Exec, on fait juste for loop dedans :grin:

**Comment by ldionmarcil** [comment]
Ça se peut tu que ton repo du lan soit privé? ça me retourne un 404.

2015-01-21 11:46 GMT-05:00 Danny Tran <notifications@github.com>:

**Comment by dannytranlx** [comment]
Ah ben oui toé, my bad!

Sample `_authors.yml` :

```yml
# Authors
firelx:
    name: Danny Tran
    display_name: firelx
    gravatar: 940f27500a75d09b8196ef9f4c0886ed
    email: dtran@lanets.ca
    web: http://dannytran.ca
    twitter: dannytranlx
    github: dannytranlx
    bio: Here goes the author description. You might want to place some links too in here
haeky:
    name: Laurent Dang
    display_name: haeky
    gravatar: c8f92f559d4e011adad194fde648e432
    email: ldang@lanets.ca
    web: http://laurentdang.com
    twitter: laurentdang
    github: haeky
    bio: Here goes the author description. You might want to place some links too in here
```
